import { perspective, lookAt, multiply, translationScale } from './mat4.js';
import { add, scale, length, sub, normalize } from '../math/vec3.js';

const VS=`#version 300 es
precision highp float;
layout(location=0) in vec3 aPos;
layout(location=1) in vec3 aNormal;
uniform mat4 uModel;
uniform mat4 uViewProj;
out vec3 vWorld;
out vec3 vNormal;
void main(){vec4 world=uModel*vec4(aPos,1.0);vWorld=world.xyz;vNormal=normalize(mat3(uModel)*aNormal);gl_Position=uViewProj*world;}`;
const FS=`#version 300 es
precision highp float;
in vec3 vWorld;in vec3 vNormal;uniform vec3 uColor;uniform vec3 uCamera;uniform vec3 uFogColor;uniform float uEmissive;out vec4 outColor;
void main(){vec3 L=normalize(vec3(-0.42,0.82,0.34));float diff=max(dot(normalize(vNormal),L),0.0);float light=0.40+diff*0.72;vec3 col=uColor*mix(light,1.0,uEmissive);float d=distance(vWorld,uCamera);float fog=smoothstep(180.0,430.0,d);col=mix(col,uFogColor,fog);outColor=vec4(col,1.0);}`;
const LINE_VS=`#version 300 es
precision highp float;layout(location=0) in vec3 aPos;uniform mat4 uViewProj;void main(){gl_Position=uViewProj*vec4(aPos,1.0);}`;
const LINE_FS=`#version 300 es
precision highp float;uniform vec4 uColor;out vec4 outColor;void main(){outColor=uColor;}`;

function shader(gl,type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s;}
function program(gl,vs,fs){const p=gl.createProgram();gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,vs));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p;}

const CUBE=[.5,-.5,-.5,1,0,0,.5,.5,-.5,1,0,0,.5,.5,.5,1,0,0,.5,-.5,-.5,1,0,0,.5,.5,.5,1,0,0,.5,-.5,.5,1,0,0,-.5,-.5,.5,-1,0,0,-.5,.5,.5,-1,0,0,-.5,.5,-.5,-1,0,0,-.5,-.5,.5,-1,0,0,-.5,.5,-.5,-1,0,0,-.5,-.5,-.5,-1,0,0,-.5,.5,-.5,0,1,0,-.5,.5,.5,0,1,0,.5,.5,.5,0,1,0,-.5,.5,-.5,0,1,0,.5,.5,.5,0,1,0,.5,.5,-.5,0,1,0,-.5,-.5,.5,0,-1,0,-.5,-.5,-.5,0,-1,0,.5,-.5,-.5,0,-1,0,-.5,-.5,.5,0,-1,0,.5,-.5,-.5,0,-1,0,.5,-.5,.5,0,-1,0,.5,-.5,.5,0,0,1,.5,.5,.5,0,0,1,-.5,.5,.5,0,0,1,.5,-.5,.5,0,0,1,-.5,.5,.5,0,0,1,-.5,-.5,.5,0,0,1,-.5,-.5,-.5,0,0,-1,-.5,.5,-.5,0,0,-1,.5,.5,-.5,0,0,-1,-.5,-.5,-.5,0,0,-1,.5,.5,-.5,0,0,-1,.5,-.5,-.5,0,0,-1];
const PYRAMID=[-.5,-.5,.5,0,-1,0,.5,-.5,.5,0,-1,0,.5,-.5,-.5,0,-1,0,-.5,-.5,.5,0,-1,0,.5,-.5,-.5,0,-1,0,-.5,-.5,-.5,0,-1,0,-.5,-.5,.5,0,.55,.83,.5,-.5,.5,0,.55,.83,0,.5,0,0,.55,.83,.5,-.5,.5,.83,.55,0,.5,-.5,-.5,.83,.55,0,0,.5,0,.83,.55,0,.5,-.5,-.5,0,.55,-.83,-.5,-.5,-.5,0,.55,-.83,0,.5,0,0,.55,-.83,-.5,-.5,-.5,-.83,.55,0,-.5,-.5,.5,-.83,.55,0,0,.5,0,-.83,.55,0];
function makeMesh(gl,data){const vao=gl.createVertexArray();gl.bindVertexArray(vao);const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,24,12);gl.bindVertexArray(null);return{vao,count:data.length/6};}

export class Renderer{
constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!this.gl)throw new Error('WebGL2 is required');const gl=this.gl;this.solidProgram=program(gl,VS,FS);this.lineProgram=program(gl,LINE_VS,LINE_FS);this.cube=makeMesh(gl,CUBE);this.pyramid=makeMesh(gl,PYRAMID);this.lineVao=gl.createVertexArray();this.lineBuf=gl.createBuffer();gl.bindVertexArray(this.lineVao);gl.bindBuffer(gl.ARRAY_BUFFER,this.lineBuf);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,12,0);gl.bindVertexArray(null);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.cullFace(gl.BACK);this.fog=[0.63,0.75,0.88];this.viewProj=null;}
resize(){const dpr=Math.min(devicePixelRatio||1,2);const w=Math.max(1,Math.floor(this.canvas.clientWidth*dpr));const h=Math.max(1,Math.floor(this.canvas.clientHeight*dpr));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;}this.gl.viewport(0,0,w,h);}
drawObject(obj,camera,emissive=0){const gl=this.gl;const center={x:(obj.min.x+obj.max.x)/2,y:(obj.min.y+obj.max.y)/2,z:(obj.min.z+obj.max.z)/2};const size={x:obj.max.x-obj.min.x,y:obj.max.y-obj.min.y,z:obj.max.z-obj.min.z};if(length(sub(center,camera.position))>470)return;gl.useProgram(this.solidProgram);const mesh=(obj.kind==='roof'||obj.kind==='spire')?this.pyramid:this.cube;gl.bindVertexArray(mesh.vao);gl.uniformMatrix4fv(gl.getUniformLocation(this.solidProgram,'uModel'),false,new Float32Array(translationScale(center,size)));gl.uniformMatrix4fv(gl.getUniformLocation(this.solidProgram,'uViewProj'),false,new Float32Array(this.viewProj));gl.uniform3fv(gl.getUniformLocation(this.solidProgram,'uColor'),obj.color??[.7,.7,.7]);gl.uniform3fv(gl.getUniformLocation(this.solidProgram,'uCamera'),[camera.position.x,camera.position.y,camera.position.z]);gl.uniform3fv(gl.getUniformLocation(this.solidProgram,'uFogColor'),this.fog);gl.uniform1f(gl.getUniformLocation(this.solidProgram,'uEmissive'),emissive);gl.drawArrays(gl.TRIANGLES,0,mesh.count);}
drawLines(points,color=[.92,.96,1,1]){if(points.length<2)return;const gl=this.gl;const data=[];for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1];data.push(a.x,a.y,a.z,b.x,b.y,b.z);}gl.useProgram(this.lineProgram);gl.bindVertexArray(this.lineVao);gl.bindBuffer(gl.ARRAY_BUFFER,this.lineBuf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.DYNAMIC_DRAW);gl.uniformMatrix4fv(gl.getUniformLocation(this.lineProgram,'uViewProj'),false,new Float32Array(this.viewProj));gl.uniform4fv(gl.getUniformLocation(this.lineProgram,'uColor'),color);gl.drawArrays(gl.LINES,0,data.length/3);}
render({world,player,camera,aimHit}){this.resize();const gl=this.gl;gl.clearColor(...this.fog,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const proj=perspective(camera.fov,this.canvas.width/this.canvas.height,.08,700);const view=lookAt(camera.position,add(camera.position,camera.forward),camera.up??{x:0,y:1,z:0});this.viewProj=multiply(proj,view);this.drawObject({min:{x:-330,y:-.7,z:-330},max:{x:330,y:0,z:330},color:[.19,.28,.22],kind:'box'},camera);this.drawObject({min:{x:-82,y:.01,z:-82},max:{x:82,y:.12,z:82},color:[.47,.48,.47],kind:'box'},camera);for(const b of world.boxes)this.drawObject(b,camera);for(const d of world.decorations)this.drawObject(d,camera);const p=player.position;this.drawObject({min:{x:p.x-.38,y:p.y-.68,z:p.z-.28},max:{x:p.x+.38,y:p.y+.62,z:p.z+.28},color:[.08,.10,.16],kind:'box'},camera);this.drawObject({min:{x:p.x-.27,y:p.y+.58,z:p.z-.27},max:{x:p.x+.27,y:p.y+1.12,z:p.z+.27},color:[.80,.72,.64],kind:'box'},camera);this.drawObject({min:{x:p.x-.55,y:p.y+.08,z:p.z-.17},max:{x:p.x-.37,y:p.y+.30,z:p.z+.17},color:[.72,.54,.18],kind:'box'},camera,0.15);this.drawObject({min:{x:p.x+.37,y:p.y+.08,z:p.z-.17},max:{x:p.x+.55,y:p.y+.30,z:p.z+.17},color:[.72,.54,.18],kind:'box'},camera,0.15);for(const [side,web] of Object.entries(player.webs)){if(!web.attached)continue;const hand={x:p.x+(side==='left'?-.46:.46),y:p.y+.22,z:p.z};const pts=web.pivot?[hand,web.pivot,web.anchor]:[hand,web.anchor];this.drawLines(pts,side==='left'?[.72,.90,1,1]:[1,.88,.72,1]);}if(aimHit){const q=aimHit.point;this.drawObject({min:{x:q.x-.16,y:q.y-.16,z:q.z-.16},max:{x:q.x+.16,y:q.y+.16,z:q.z+.16},color:[1,.78,.2],kind:'box'},camera,1);}}
}
